### PR TITLE
Add `customHeaderComponent`

### PR DESCRIPTION
**Pull request by kivircik-parantez**
I needed a custom header field to be able to change the header component and add it. Can you provide this kind of field or approve this pull request or I can open an issue instead?

### CODE REVIEW

**Comment by nick-keller** [comment]
What is the intended purpose ? Can't you simply use the `title` key of the column to show a custom component ?

**Comment by kivircik-parantez** [comment]
It wasn't enough for the header groupings, I had to intervene and add my own custom header.
Like this. 
image

**Comment by seriojca** [comment]
I also curious about the custom components in header, for the exact same need of column groupings.

**Comment by nick-keller** [comment]
I understand the issue you are trying to solve here, but we cannot expose the implementation of virtualisers to the outside.

**Pull request closed without merging**
