### PR TITLE
Manage cells in error

### PR DESCRIPTION
**Pull request by Pamwamba**
Highlights cells that are in errors, from an array passed in DataSheetGrid props.

I added this for my use case :
1) I integrate my data to the grid
2) I click on an "Import" button
3) The back-end check for errors, then return cells that are in errors 
4) I highlight my cells with this prop.

### CODE REVIEW

**Review by nick-keller — COMMENTED** [review]
Thanks for the contribution!
I am not going to merge this work for now for the following reasons:

- It is already possible to achieve this without changing the API by using the `cellClassName` prop.
- It is too basic for most use cases, we probably want to add the error message.

But I am planning on integrating errors out of the box by providing the right components as I do with basic columns. You can expect it to ship in the coming months.

**Comment by Pamwamba** [comment]
Thanks for your time,

We will wait for this feature that could add a lot of benefits to our app.

You say we can use the cellClassName to add a class to specifics cells, is it right ? Or does it change all cells classnames ?

**Comment by nick-keller** [comment]
You can pass [a function](https://react-datasheet-grid.netlify.app/docs/api-reference/columns#cellclassname) to target specific cells only.

For all projects I worked on that use this component, we also add a triangle at the top right corner to display the error with a tooltip, to achieve this we wrap all components of all columns in a component that simply display the triangle and forwards all props to the initial component.

**Comment by Pamwamba** [comment]
> You can pass [a function](https://react-datasheet-grid.netlify.app/docs/api-reference/columns#cellclassname) to target specific cells only.
> 
> For all projects I worked on that use this component, we also add a triangle at the top right corner to display the error with a tooltip, to achieve this we wrap all components of all columns in a component that simply display the triangle and forwards all props to the initial component.

I managed to do it, thank you, i'll close this PR

**Pull request closed without merging**
